### PR TITLE
Added an ignore flag

### PR DESCRIPTION
**Pull request by shumphrey**
I've added an ignore flag. This allows you to do something like 

```
prereq-grapher -ignore "^Moose" My::Module
```

Then Moose no longer appears in your generate dot file.

I also added to the tests and pod for this functionality.

### CODE REVIEW

**Comment by bjakubski** [comment]
I'd like to have a possibility of generating graph only for selected namespace (ignoring all modules not matching selected namespace/pattern). I wanted to visualize dependencies between modules in my large internal codebase (everything is in my private namespace), while I'm not interested in perl/CPAN dependencies.
So I have huge Foo::* project and I want to see graph for Foo::Bar but limited to Foo:: modules. Or maybe to Foo:: and Baz:: (internal subproject).

**Comment by pmorch** [comment]
I discovered I need this as well. 

[on Dec 10, 2012](https://github.com/neilb/App-PrereqGrapher/pull/2#issuecomment-11196988) @neilb wrote:
> I'll think about this more later, as there are some other options in this vein I'm thinking about too :-)

I agree that eventually there should be (at least) two options - one for behaviour like `-no-core` and one for behaviour like `-no-recurse-core`.

Unless @neilb has a better suggestion, may I suggest a pragmatic approach of adding two attributes to `App::PrereqGrapher`, that initially aren't supported by command-line options?

```perl
has include_module_sub => (
    is => 'ro',
    isa => sub { croak "include_module_sub must be an coderef\n" unless ref($_[0]) eq 'CODE'; },
);

has recurse_module_sub => (
    is => 'ro',
    isa => sub { croak "recurse_module_sub must be an coderef\n" unless ref($_[0]) eq 'CODE'; },
);
```

And then a diff somewhat like this for the `foreach` loop in `App::PrereqGrapher::generate_graph`:
```diff
--- foreach-loop.pl	2017-04-28 18:37:23.170134738 +0200
+++ foreach-loop-new.pl	2017-04-28 18:37:12.830134738 +0200
@@ -2,13 +2,13 @@
     if (!exists($depth{$dep}) || $depth{$dep} > $depth{$module} + 1) {
         $depth{$dep} = $depth{$module} + 1;
     }
-    if ($self->no_core && is_core($dep)) {
+    if ($self->no_core && is_core($dep) || ! $self->include_module_sub->($dep)) {
         # don't include core modules
     } elsif ($dep eq 'perl') {
         $graph->add_edge($module, "perl $depsref->{perl}");
     } else {
         $graph->add_edge($module, $dep);
         next if $self->depth && $depth{$dep} >= $self->depth;
-        push(@queue, $dep) unless $self->no_recurse_core && is_core($dep);
+        push(@queue, $dep) if (! $self->no_recurse_core || ! is_core($dep)) && $self->recurse_module_sub->($dep);
     }
 }
```
This just shows the approach. Closer to reality, move the if clauses to separate methods `ignore_module` and `recurse_module`, test for `undef`, fix comments, etc.

Even better, `include_module_subs` and `recurse_module_subs` (now with `s`) could be arrays of subs, all of which have to return true for a given `$dep`. Then `-no-core` and `-no-recurse-core` can be implemented as elements in these arrays.

Then we could all write our own wrappers instead of the 4-line `bin/prereq-grapher` with our own code for the two new attributes.

Now these attributes provide the plumbing for any future command-line options. Future comments to this issue could showcase handy implementations of them before deciding on actual command-line options. Whatever the choice of command-line options these are the two atomic behaviours that they need.

I'm happy to do it if we can agree on the approach.

**Comment by shumphrey** [comment]
This PR has been open since 2012, I'm going to close it now, it'll be in the GitHub history if required.
I'm no longer actively using perl so am not motivated to do anything with this PR

**Comment by pmorch** [comment]
I'm also not using perl any longer, I don't need it either.

**Pull request closed without merging**
